updating action again.

diff --git a/.github/workflows/github-actions-main.yml b/.github/workflows/github-actions-main.yml
--- a/.github/workflows/github-actions-main.yml
+++ b/.github/workflows/github-actions-main.yml
@@ -3,18 +3,35 @@ on: [push, pull_request]
 jobs:
   Main:
     # We always process server or desktop release tags, because they also publish the release
-    if: github.repository == 'laurent22/joplin'
+    if: github.repository == 'sahal/joplin'
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
         # https://github.com/actions/runner-images/issues/6709
-        os: [macos-13, ubuntu-22.04, windows-2019, ubuntu-22.04-arm]
+        os: [ubuntu-22.04]
     steps:
-      - uses: actions/checkout@v4
 
-      - name: Setup build environment
-        uses: ./.github/workflows/shared/setup-build-environment
+      - name: Disable TCP/UDP offload on Linux
+        if: runner.os == 'Linux'
+        run: sudo ethtool -K eth0 tx off rx off
+
+      # Silence apt-get update errors (for example when a module doesn't
+      # exist) since otherwise it will make the whole build fails, even though
+      # it might work without update. libsecret-1-dev is required for keytar -
+      # https://github.com/atom/node-keytar
+
+      - name: Install Linux dependencies
+        if: runner.os == 'Linux'
+        run: |
+          sudo apt-get update || true
+          sudo apt-get install -y gettext
+          sudo apt-get install -y libsecret-1-dev
+          sudo apt-get install -y translate-toolkit
+          sudo apt-get install -y rsync
+          # Provides a virtual display on Linux. Used for Playwright integration
+          # testing.
+          sudo apt-get install -y xvfb
 
       - name: Install Docker Engine
         # if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/server-v')
@@ -27,10 +44,25 @@ jobs:
           sudo apt-get install -y lsb-release
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
           echo \
-              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
+              "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update || true
-          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+
+      - uses: actions/checkout@v4
+      - uses: olegtarasov/get-tag@v2.1.3
+      - uses: dtolnay/rust-toolchain@stable
+      - uses: actions/setup-node@v4
+        with:
+          # We need to pin the version to 18.15, because 18.16+ fails with this error:
+          # https://github.com/facebook/react-native/issues/36440
+          node-version: '23.2.0'
+          cache: 'yarn'
+
+      - name: Install Yarn
+        run: |
+          # https://yarnpkg.com/getting-started/install
+          corepack enable
 
       # Login to Docker only if we're on a server release tag. If we run this on
       # a pull request it will fail because the PR doesn't have access to
@@ -40,6 +72,15 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      # macos-latest ships with Python 3.12 by default, but this removes a
+      # utility that's used by electron-builder (distutils) so we need to pin
+      # Python to an earlier version.
+      # Fixes error `ModuleNotFoundError: No module named 'distutils'`
+      # Ref: https://github.com/nodejs/node-gyp/issues/2869
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
 
       - name: Run tests, build and publish Linux and macOS apps
         if: runner.os == 'Linux' || runner.os == 'macOs'
@@ -84,23 +125,14 @@ jobs:
         run: |
           yarn install && cd packages/app-desktop && yarn dist --publish=never
 
-      - name: Publish Docker manifest
-        if: runner.os == 'Linux'
-        env:
-          SERVER_REPOSITORY: joplin/server
-          SERVER_TAG_PREFIX: server
-        run: |
-          chmod 700 "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
-          "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
-
   ServerDockerImage:
-    if: github.repository == 'laurent22/joplin'
+    if: github.repository == 'sahal/joplin'
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
         # https://github.com/actions/runner-images/issues/6709
-        os: [ubuntu-22.04, ubuntu-22.04-arm]
+        os: [ubuntu-22.04]
     steps:
 
       - name: Install Docker Engine
@@ -112,16 +144,16 @@ jobs:
           sudo apt-get install -y lsb-release
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
           echo \
-              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
+              "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update || true
-          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
 
       - uses: actions/checkout@v4
 
       - uses: actions/setup-node@v4
         with:
-          node-version: '18'
+          node-version: '23.2.0'
           cache: 'yarn'
 
       - name: Install Yarn
@@ -133,26 +165,13 @@ jobs:
         env:
           BUILD_SEQUENCIAL: 1
         run: |
-          if [ "$RUNNER_ARCH" == "ARM64" ]; then
-            DOCKER_IMAGE_PLATFORM="linux/arm64"
-          fi
-
-          echo "RUNNER_OS=$RUNNER_OS"
-          echo "RUNNER_ARCH=$RUNNER_ARCH"
-          echo "DOCKER_IMAGE_PLATFORM=$DOCKER_IMAGE_PLATFORM"
-
-          # Canvas is only needed for tests and it doesn't build in ARM64 so remove it
-          cd packages/lib
-          yarn remove canvas
-          cd ../..
-          
           yarn install
-          yarn buildServerDocker --platform $DOCKER_IMAGE_PLATFORM --tag-name server-v0.0.0 --repository joplin/server
+          yarn buildServerDocker --tag-name server-v0.0.0 --repository joplin/server
 
           # Basic test to ensure that the created build is valid. It should exit with
-          # code 0 if it works.
+          # code 0  if it works.
           docker run joplin/server:0.0.0-beta node dist/app.js migrate list
- 
+
       - name: Check HTTP request
         run: |
           # Need to pass environment variables:
@@ -164,21 +183,21 @@ jobs:
           # Check if status code is correct
           # if the actual_status DOES NOT include the expected_status
           # it exits the process with code 1
-          
+
           expected_status="HTTP/1.1 200 OK"
           actual_status=$(curl -I -X GET http://localhost:22300/api/ping | head -n 1)
-          if [[ ! "$actual_status" =~ "$expected_status" ]]; then 
+          if [[ ! "$actual_status" =~ "$expected_status" ]]; then
             echo 'Failed while checking the status code after request to /api/ping'
             echo 'expected: ' $expected_status
             echo 'actual:   ' $actual_status
-            exit 1; 
+            exit 1;
           fi
-          
+
           # Check if the body response is correct
           # if the actual_body is different of expected_body exit with code 1
           expected_body='{"status":"ok","message":"Joplin Server is running"}'
           actual_body=$(curl http://localhost:22300/api/ping)
-          
+
           if [[ "$actual_body" != "$expected_body" ]]; then
             echo 'Failed while checking the body response after request to /api/ping'
             exit 1;
